USE [master]
GO

/****** Object:  Database [PCPartsDB]    Script Date: 2/11/2022 9:48:46 PM ******/
CREATE DATABASE [PCPartsDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PCPartsDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PCPartsDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PCPartsDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PCPartsDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PCPartsDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PCPartsDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PCPartsDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PCPartsDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PCPartsDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PCPartsDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [PCPartsDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PCPartsDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PCPartsDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PCPartsDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PCPartsDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PCPartsDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PCPartsDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PCPartsDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PCPartsDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PCPartsDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PCPartsDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PCPartsDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PCPartsDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PCPartsDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PCPartsDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PCPartsDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PCPartsDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PCPartsDB] SET RECOVERY FULL 
GO

ALTER DATABASE [PCPartsDB] SET  MULTI_USER 
GO

ALTER DATABASE [PCPartsDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PCPartsDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PCPartsDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PCPartsDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PCPartsDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PCPartsDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PCPartsDB] SET  READ_WRITE 
GO


